require "./curl"

@[Link("libcurl")]
lib Easy
  alias Curl = Void

  alias Int = LibC::Int
  alias Char = LibC::Char
  alias SizeT = LibC::SizeT
  alias Curlcode = Curl::Curlcode

  enum Curloption
    CurloptWritedata               = 10001
    CurloptUrl                     = 10002
    CurloptPort                    =     3
    CurloptProxy                   = 10004
    CurloptUserpwd                 = 10005
    CurloptProxyuserpwd            = 10006
    CurloptRange                   = 10007
    CurloptReaddata                = 10009
    CurloptErrorbuffer             = 10010
    CurloptWritefunction           = 20011
    CurloptReadfunction            = 20012
    CurloptTimeout                 =    13
    CurloptInfilesize              =    14
    CurloptPostfields              = 10015
    CurloptReferer                 = 10016
    CurloptFtpport                 = 10017
    CurloptUseragent               = 10018
    CurloptLowSpeedLimit           =    19
    CurloptLowSpeedTime            =    20
    CurloptResumeFrom              =    21
    CurloptCookie                  = 10022
    CurloptHttpheader              = 10023
    CurloptHttppost                = 10024
    CurloptSslcert                 = 10025
    CurloptKeypasswd               = 10026
    CurloptCrlf                    =    27
    CurloptQuote                   = 10028
    CurloptHeaderdata              = 10029
    CurloptCookiefile              = 10031
    CurloptSslversion              =    32
    CurloptTimecondition           =    33
    CurloptTimevalue               =    34
    CurloptCustomrequest           = 10036
    CurloptStderr                  = 10037
    CurloptPostquote               = 10039
    CurloptObsolete40              = 10040
    CurloptVerbose                 =    41
    CurloptHeader                  =    42
    CurloptNoprogress              =    43
    CurloptNobody                  =    44
    CurloptFailonerror             =    45
    CurloptUpload                  =    46
    CurloptPost                    =    47
    CurloptDirlistonly             =    48
    CurloptAppend                  =    50
    CurloptNetrc                   =    51
    CurloptFollowlocation          =    52
    CurloptTransfertext            =    53
    CurloptPut                     =    54
    CurloptProgressfunction        = 20056
    CurloptProgressdata            = 10057
    CurloptAutoreferer             =    58
    CurloptProxyport               =    59
    CurloptPostfieldsize           =    60
    CurloptHttpproxytunnel         =    61
    CurloptInterface               = 10062
    CurloptKrblevel                = 10063
    CurloptSslVerifypeer           =    64
    CurloptCainfo                  = 10065
    CurloptMaxredirs               =    68
    CurloptFiletime                =    69
    CurloptTelnetoptions           = 10070
    CurloptMaxconnects             =    71
    CurloptObsolete72              =    72
    CurloptFreshConnect            =    74
    CurloptForbidReuse             =    75
    CurloptRandomFile              = 10076
    CurloptEgdsocket               = 10077
    CurloptConnecttimeout          =    78
    CurloptHeaderfunction          = 20079
    CurloptHttpget                 =    80
    CurloptSslVerifyhost           =    81
    CurloptCookiejar               = 10082
    CurloptSslCipherList           = 10083
    CurloptHttpVersion             =    84
    CurloptFtpUseEpsv              =    85
    CurloptSslcerttype             = 10086
    CurloptSslkey                  = 10087
    CurloptSslkeytype              = 10088
    CurloptSslengine               = 10089
    CurloptSslengineDefault        =    90
    CurloptDnsUseGlobalCache       =    91
    CurloptDnsCacheTimeout         =    92
    CurloptPrequote                = 10093
    CurloptDebugfunction           = 20094
    CurloptDebugdata               = 10095
    CurloptCookiesession           =    96
    CurloptCapath                  = 10097
    CurloptBuffersize              =    98
    CurloptNosignal                =    99
    CurloptShare                   = 10100
    CurloptProxytype               =   101
    CurloptAcceptEncoding          = 10102
    CurloptPrivate                 = 10103
    CurloptHttp200aliases          = 10104
    CurloptUnrestrictedAuth        =   105
    CurloptFtpUseEprt              =   106
    CurloptHttpauth                =   107
    CurloptSslCtxFunction          = 20108
    CurloptSslCtxData              = 10109
    CurloptFtpCreateMissingDirs    =   110
    CurloptProxyauth               =   111
    CurloptFtpResponseTimeout      =   112
    CurloptIpresolve               =   113
    CurloptMaxfilesize             =   114
    CurloptInfilesizeLarge         = 30115
    CurloptResumeFromLarge         = 30116
    CurloptMaxfilesizeLarge        = 30117
    CurloptNetrcFile               = 10118
    CurloptUseSsl                  =   119
    CurloptPostfieldsizeLarge      = 30120
    CurloptTcpNodelay              =   121
    CurloptFtpsslauth              =   129
    CurloptIoctlfunction           = 20130
    CurloptIoctldata               = 10131
    CurloptFtpAccount              = 10134
    CurloptCookielist              = 10135
    CurloptIgnoreContentLength     =   136
    CurloptFtpSkipPasvIp           =   137
    CurloptFtpFilemethod           =   138
    CurloptLocalport               =   139
    CurloptLocalportrange          =   140
    CurloptConnectOnly             =   141
    CurloptConvFromNetworkFunction = 20142
    CurloptConvToNetworkFunction   = 20143
    CurloptConvFromUtf8Function    = 20144
    CurloptMaxSendSpeedLarge       = 30145
    CurloptMaxRecvSpeedLarge       = 30146
    CurloptFtpAlternativeToUser    = 10147
    CurloptSockoptfunction         = 20148
    CurloptSockoptdata             = 10149
    CurloptSslSessionidCache       =   150
    CurloptSshAuthTypes            =   151
    CurloptSshPublicKeyfile        = 10152
    CurloptSshPrivateKeyfile       = 10153
    CurloptFtpSslCcc               =   154
    CurloptTimeoutMs               =   155
    CurloptConnecttimeoutMs        =   156
    CurloptHttpTransferDecoding    =   157
    CurloptHttpContentDecoding     =   158
    CurloptNewFilePerms            =   159
    CurloptNewDirectoryPerms       =   160
    CurloptPostredir               =   161
    CurloptSshHostPublicKeyMd5     = 10162
    CurloptOpensocketfunction      = 20163
    CurloptOpensocketdata          = 10164
    CurloptCopypostfields          = 10165
    CurloptProxyTransferMode       =   166
    CurloptSeekfunction            = 20167
    CurloptSeekdata                = 10168
    CurloptCrlfile                 = 10169
    CurloptIssuercert              = 10170
    CurloptAddressScope            =   171
    CurloptCertinfo                =   172
    CurloptUsername                = 10173
    CurloptPassword                = 10174
    CurloptProxyusername           = 10175
    CurloptProxypassword           = 10176
    CurloptNoproxy                 = 10177
    CurloptTftpBlksize             =   178
    CurloptSocks5GssapiService     = 10179
    CurloptSocks5GssapiNec         =   180
    CurloptProtocols               =   181
    CurloptRedirProtocols          =   182
    CurloptSshKnownhosts           = 10183
    CurloptSshKeyfunction          = 20184
    CurloptSshKeydata              = 10185
    CurloptMailFrom                = 10186
    CurloptMailRcpt                = 10187
    CurloptFtpUsePret              =   188
    CurloptRtspRequest             =   189
    CurloptRtspSessionId           = 10190
    CurloptRtspStreamUri           = 10191
    CurloptRtspTransport           = 10192
    CurloptRtspClientCseq          =   193
    CurloptRtspServerCseq          =   194
    CurloptInterleavedata          = 10195
    CurloptInterleavefunction      = 20196
    CurloptWildcardmatch           =   197
    CurloptChunkBgnFunction        = 20198
    CurloptChunkEndFunction        = 20199
    CurloptFnmatchFunction         = 20200
    CurloptChunkData               = 10201
    CurloptFnmatchData             = 10202
    CurloptResolve                 = 10203
    CurloptTlsauthUsername         = 10204
    CurloptTlsauthPassword         = 10205
    CurloptTlsauthType             = 10206
    CurloptTransferEncoding        =   207
    CurloptClosesocketfunction     = 20208
    CurloptClosesocketdata         = 10209
    CurloptGssapiDelegation        =   210
    CurloptDnsServers              = 10211
    CurloptAccepttimeoutMs         =   212
    CurloptTcpKeepalive            =   213
    CurloptTcpKeepidle             =   214
    CurloptTcpKeepintvl            =   215
    CurloptSslOptions              =   216
    CurloptMailAuth                = 10217
    CurloptSaslIr                  =   218
    CurloptXferinfofunction        = 20219
    CurloptXoauth2Bearer           = 10220
    CurloptDnsInterface            = 10221
    CurloptDnsLocalIp4             = 10222
    CurloptDnsLocalIp6             = 10223
    CurloptLoginOptions            = 10224
    CurloptSslEnableNpn            =   225
    CurloptSslEnableAlpn           =   226
    CurloptExpect100TimeoutMs      =   227
    CurloptProxyheader             = 10228
    CurloptHeaderopt               =   229
    CurloptPinnedpublickey         = 10230
    CurloptUnixSocketPath          = 10231
    CurloptSslVerifystatus         =   232
    CurloptSslFalsestart           =   233
    CurloptPathAsIs                =   234
    CurloptProxyServiceName        = 10235
    CurloptServiceName             = 10236
    CurloptPipewait                =   237
    CurloptLastentry               =   238
  end

  enum Curlinfo
    CurlinfoNone                  =       0
    CurlinfoEffectiveUrl          = 1048577
    CurlinfoResponseCode          = 2097154
    CurlinfoTotalTime             = 3145731
    CurlinfoNamelookupTime        = 3145732
    CurlinfoConnectTime           = 3145733
    CurlinfoPretransferTime       = 3145734
    CurlinfoSizeUpload            = 3145735
    CurlinfoSizeDownload          = 3145736
    CurlinfoSpeedDownload         = 3145737
    CurlinfoSpeedUpload           = 3145738
    CurlinfoHeaderSize            = 2097163
    CurlinfoRequestSize           = 2097164
    CurlinfoSslVerifyresult       = 2097165
    CurlinfoFiletime              = 2097166
    CurlinfoContentLengthDownload = 3145743
    CurlinfoContentLengthUpload   = 3145744
    CurlinfoStarttransferTime     = 3145745
    CurlinfoContentType           = 1048594
    CurlinfoRedirectTime          = 3145747
    CurlinfoRedirectCount         = 2097172
    CurlinfoPrivate               = 1048597
    CurlinfoHttpConnectcode       = 2097174
    CurlinfoHttpauthAvail         = 2097175
    CurlinfoProxyauthAvail        = 2097176
    CurlinfoOsErrno               = 2097177
    CurlinfoNumConnects           = 2097178
    CurlinfoSslEngines            = 4194331
    CurlinfoCookielist            = 4194332
    CurlinfoLastsocket            = 2097181
    CurlinfoFtpEntryPath          = 1048606
    CurlinfoRedirectUrl           = 1048607
    CurlinfoPrimaryIp             = 1048608
    CurlinfoAppconnectTime        = 3145761
    CurlinfoCertinfo              = 4194338
    CurlinfoConditionUnmet        = 2097187
    CurlinfoRtspSessionId         = 1048612
    CurlinfoRtspClientCseq        = 2097189
    CurlinfoRtspServerCseq        = 2097190
    CurlinfoRtspCseqRecv          = 2097191
    CurlinfoPrimaryPort           = 2097192
    CurlinfoLocalIp               = 1048617
    CurlinfoLocalPort             = 2097194
    CurlinfoTlsSession            = 4194347
    CurlinfoLastone               =      43
  end

  fun init = curl_easy_init : Curl*
  fun escape = curl_easy_escape(handle : Curl*, string : Char*, length : Int) : Char*
  fun unescape = curl_easy_unescape(handle : Curl*, string : Char*, length : Int, outlength : Int*) : Char*
  fun strerror = curl_easy_strerror(x0 : Curlcode) : Char*
  fun pause = curl_easy_pause(handle : Curl*, bitmask : Int) : Curlcode
  fun setopt = curl_easy_setopt(curl : Curl*, option : Curloption, ...) : Curlcode
  fun perform = curl_easy_perform(curl : Curl*) : Curlcode
  fun cleanup = curl_easy_cleanup(curl : Curl*)
  fun getinfo = curl_easy_getinfo(curl : Curl*, info : Curlinfo, ...) : Curlcode
  fun duphandle = curl_easy_duphandle(curl : Curl*) : Curl*
  fun reset = curl_easy_reset(curl : Curl*)
  fun recv = curl_easy_recv(curl : Curl*, buffer : Void*, buflen : SizeT, n : SizeT*) : Curlcode
  fun send = curl_easy_send(curl : Curl*, buffer : Void*, buflen : SizeT, n : SizeT*) : Curlcode
end
